spring.application.name=avatar-questions-backend

# H2
spring.datasource.url=jdbc:h2:file:./data/avatarquestions
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console (accessible at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080

# Google OAuth
google.client.id=1043723395645-a0k5uqvrcne42fnhle8kvahmi1meheau.apps.googleusercontent.com
